name: Crowdin Action

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
        
    - name: setup
      env:
        ALGOLIA_API_KEY: ${{secrets.ALGOLIA_API_KEY}}
        ALGOLIA_APP_ID: ${{secrets.ALGOLIA_APP_ID}}
        ALGOLIA_INDEX_NAME: ${{secrets.ALGOLIA_INDEX_NAME}}
      run : |
        yarn install --frozen-lockfile
        yarn run write-translations

    - name: crowdin action
      run: |
        yarn add @crowdin/cli@3
        yarn run crowdin upload -T=${{ secrets.CROWDIN_PERSONAL_TOKEN }} -i=${{ secrets.CROWDIN_PROJECT_ID}}
        
